name: bhavani_medical_erp
description: Bhavani Medicals ERP with Billing, Stock, GST
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  pdf: ^3.10.7
  printing: ^5.11.1
  intl: ^0.19.0
  flutter_slidable: ^3.0.1

flutter:
  uses-material-design: true
