name: Build Bhavani Medical APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build APK Release
        run: flutter build apk --release
      
      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Bhavani-Medical-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
